### ISSUE TITLE
Is multi-seat / multi-pointer / multi-focus supported or planned?

### ISSUE THREAD

**Issue by Ape** [SirCmpwn/sway#1054]
I'm looking for a tiling window manager for Wayland that supports multi-seat / multi-pointer / multi-focus features ([example](https://www.youtube.com/watch?v=WO2L_ihO_rI)). Are these features supported or planned for sway?

Mainly I am looking support for a concept of multi-focus where different sets of pointers and keyboards would have their own focus (perhaps visually color coded on the windows). Wayland itself would allow the features.

**Comment by SirCmpwn** [comment]
There's nothing officially planned for this but you're welcome to work on it if that's important to you.

**Comment by pickfire** [comment]
i3 sometimes works with multi cursor but it might just gone wrong since the mouse focus is too random so applications are jumping around.

dwm is running perfectly fine for me with multi-cursor setup (keyboard locked) but the just that the cursors are wrongly displayed.

http://pickfire.tk/posts/linux/multi-pointer

Haven't successfully tested multi seat. And haven't heard of multi-focus.

**Comment by SirCmpwn** [comment]
This is planned for wlroots.

**Comment by rektide** [comment]
Resolved in https://github.com/swaywm/wlroots/pull/352
