### ISSUE TITLE
Feature request: drop shadows

### ISSUE THREAD

**Issue by bearcatsandor** [SirCmpwn/sway#1065]
How difficult would it be to add the ability to have drop-shadows on windows, for those of us that use gaps?

**Comment by SirCmpwn** [comment]
Probably not that difficult.

**Comment by bearcatsandor** [comment]
Anychance this might make it into the roadmap, is it an addition that you'd accept?

**Comment by SirCmpwn** [comment]
I won't put it on the roadmap but I would accept a pull request.

**Comment by SirCmpwn** [comment]
No.

**Comment by topisani** [comment]
I implemented this in [tablecloth](https://github.com/topisani/tablecloth) (rootston based compositor i abandoned), and would like to implement it in sway. The aproach i used used GLESv2 directly (loading a GL shader). Would an aproach like this be accepted? maybe enabled by a macro if GLES is avaliable?
Otherwise, what would be the rendering options?
 
Config-wise, i would probably do it like border/titlebar configuration, allowing shadow color change on focus, urgent etc.

**Comment by rhysperry111** [comment]
I think this probably depends on #3652
