### ISSUE TITLE
notify-send doesn't show anything

### ISSUE THREAD

**Issue by kenny1847** [SirCmpwn/sway#1096]
So, issue-name speaks for itself.
Probably it is wlc problem.
Probably I just cooking it wrong.

Using Fedora 25.

**Comment by SirCmpwn** [comment]
Like i3, sway does not include a notification daemon. You need to use an external one like dunst.

**Comment by hobarrera** [comment]
`dunst` doesn't really work well under sway:

* It's positioned on the upper left corner regardless of config.
* Global hotkeys don't work.
* Clicks pass through it to the window behind it.

This is probably due to the way wayland is designed (eg: can't grab global hotkey, etc).

Is there any workaround for this? Am I mistaken in thinking that sway needs to explicitly support notification daemons somehow (due to the placement overriding and global hotkey grabbing).

**Comment by tidux** [comment]
`dunst` also assumes `DISPLAY=:0`, so the provided systemd user service fails to run under Sway.

**Comment by albocc** [comment]
@WhyNotHugo Did you find a good alternative? I switched to Sway recently and noticed the same.

**Comment by norpol** [comment]
Since this is one of the early search results on Google:

via [archwiki](https://wiki.archlinux.org/index.php/Desktop_notifications)
> [mako](https://github.com/emersion/mako) — A lightweight notification daemon for Wayland; it currently works on Sway.

After installing just put into your sway config.

> `exec mako`

**Comment by tidux** [comment]
I can confirm Mako works.

**Comment by Maskedman99** [comment]
Issue in dunst repository for support of wayland https://github.com/dunst-project/dunst/issues/264
