### ISSUE TITLE
Proposed changes to release cycle

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#1106]
1. Minimum of 3 rcs
2. Switching to 0.x.y and merging bugfixes into the 0.x branches and shipping .y releases with them between major releases
3. Required sign offs from various volunteer testers (from various distros, BSD guys, general purpose testers, maybe people who did substantial PRs this release cycle, etc) for major releases

We can do all, some, or none of these, or refine any of them a bit. Discuss.

**Comment by Fale** [comment]
1. I think sometimes (like for 0.12) 3 rcs seems overkilling. At least 2 is what I would go for.
2. I like it :)
3. I'm up to do some testing on building it for Fedora and on Fedora in general, as I have been doing it for the last few releases

**Comment by SirCmpwn** [comment]
Well, we missed a pretty major bug for 0.12

**Comment by Fale** [comment]
If you are talking about #1105, I think that more "generic" testing would not have found that problem either way (I can not use multiple screens due to https://github.com/Cloudef/wlc/issues/87 so I would not have that tested either way).
Probably we need to create list of tests and people can test stuff against that list and say "I tested numbers 1,3,4,5,6 and they all worked" so we can ensure that all tests have been run at least once

**Comment by sleep-walker** [comment]
1. I don't think 3 RCs are needed, but some more time between them could help. I'm packaging them as well but it takes time until it gets to wider audience.
2. As package maintainer I welcome that.
3. No opinion on this.

**Comment by SirCmpwn** [comment]
We'll do a minimum of 2 rc's, and I've already started to ship X.Y.Z releases.

Regarding testing, looking for volunteers to read over the rc's and test anything that changed.
