### ISSUE TITLE
GDM fails to start sway

### ISSUE THREAD

**Issue by lindhe** [SirCmpwn/sway#1114]
Sorry for being vague, but I literally have no idea on how to debug sway, at least not when it's crashing as much as it does for me. And my usual go-to, the Arch Wiki, does not give much advice. Also, this might turn out to be a GDM or driver issue. If so, please point me in the right direction.

### In GDM

GDM properly detects `/usr/share/wayland-sessions/sway.desktop`, so it shows up in the menu. But if I choose it and login, the screen freezes for a second and then throws me back in GDM. Rinse and repeat.

### In a TTY

If I disable GDM and try to start it from a TTY by running `sway`, it crashes by saying `[main.c:45] [wlc] Failed to init compositor` and then the entire system is frozen.

After two minutes I get a notice that some kernel worker thread have stopped responding (go figure), like this:

```
INFO: task kworker/0:1:116 blocked for more than 120 seconds.
Tainted: F      O  4.10.1-1-ARCH #1
```

### In gnome

_However_, if I try to start it from within Gnome (which I guess is running Wayland nowadays), by running `sway` in a terminal emulator, it opens up a seemingly functional windowed session.

I'm on an ASUS x99 motherboard with Intel 5960X, an NVidia GTX Titan running nouveau drivers.

**Comment by SirCmpwn** [comment]
Did you try reading the FAQ https://github.com/SirCmpwn/sway/wiki#faq

**Comment by lindhe** [comment]
I believe I have failed to do so. I'll check it out and get back.

**Comment by lindhe** [comment]
Indeed, it is well documented. :)

I looked through all issues as suggested, and found [this](https://github.com/Cloudef/wlc/issues/11). And, after checking the logs, indeed sway seemed to look for card0 without finding it. It didn't even register for me that I neglected to mention my secondary card, because it's not even plugged into a monitor. Sorry for that.

Cool. Case closed. Sway don't deal with multi GPU systems (unless one is lucky enough to have the correct card as card0).

**Comment by SirCmpwn** [comment]
try `WLC_DRM_DEVICE=card1` or whatever's appropriate

**Comment by lindhe** [comment]
Ah, I see. Thank you for the advice, but it's easier for me to just leave the second card out since I didn't use it anyway.

**Comment by francisco-colaco** [comment]
SOLUTION

FOR ONE USER ACCOUNT ONLY

In order to get GDM to start sway, create a file in the directory ~/.config/environment.d, like ~/.config/.environment.d/sway.conf with the following content.  If card0 down not work, the card will be almost always card1 and the layout should be your keyboard layout --- Portuguese in my case, so I set pt.

WLC_DRM_DEVICE=card1
XKB_DEFAULT_LAYOUT=pt

And that's it!  Logout and you can start sway from GDM.

wayland-session will not read .bash_profile, but systemd will read ~/.config/.environment.d/*.conf and thus you can define variables.

If you want to start also from the Linux console, either set and export the variables in ~/.bash_profile or include the following:

. ~/.config/environment.d/sway.conf
export WLC_DRM_DEVICE XKB_DEFAULT_LAYOUT

Using the previous content provides a single point of edition.

AT THE SYSTEM LEVEL, FOR ALL USERS

Now, if one wants to make the variables available to all users, just write them in /etc/environment, like so, adapted to your circumstances:

WLC_DRM_DEVICE=card1
XKB_DEFAULT_LAYOUT=pt

Using this, no configuration is needed at the user directories.

**Comment by ascent12** [comment]
I can confirm that sway (with wlroots) now starts perfectly fine with GDM without requiring any extra configuration.
This is only when using the logind wlr_session backend; the direct wlr_session does not work. Although this is not something I really care about, since GDM has a logind dependency anyway.

**Comment by agentzhao** [comment]
I started having this issue when I updated from Fedora Linux (6.5.9-200.fc38.x86_64) 38 (Workstation Edition) to Fedora Linux (6.5.10-200.fc38.x86_64) 38 (Workstation Edition). If I choose the 6.5.9 kernel from grub it still works perfectly fine

> WLC_DRM_DEVICE=card1 XKB_DEFAULT_LAYOUT=pt
Not sure why this is happening but this fix is not working for me

**Comment by bl4ckb0ne** [comment]
Please open a new issue. 

> Not sure why this is happening but this fix is not working for me

It's because sway is not using wlc anymore

**Comment by agentzhao** [comment]
> Please open a new issue. 
> 
> > Not sure why this is happening but this fix is not working for me
> 
> It's because sway is not using wlc anymore

ahh no wonder. I fixed it by using sddm instead of gdm. Didn't really solve the issue, probably something gdm related
