### ISSUE TITLE
Root user cannot open display :0

### ISSUE THREAD

**Issue by LucaSpinosi** [SirCmpwn/sway#1281]
Hi, when i become root with `su` command, i can't run anything that use display `:0`.
If i do that i get:
`No protocol specified`
`Error: cannot open display: :0`
To fix it i've done, as root user:
`xauth add :0 . 0123456789abcdef` 
After that if i try to run something, i get:
`Invalid MIT-MAGIC-COOKIE-1 keyError: cannot open display: :0`
But the curious thing is that, if i login inside tty0 with root user, the problem is fixed, but if i `su` another user, it comes back.

**Comment by nloewen** [comment]
This is a limitation of Wayland, not a bug.
https://wiki.archlinux.org/index.php/Wayland#Running_graphical_applications_as_root

**Comment by LucaSpinosi** [comment]
Thank you

**Comment by damko** [comment]
Please pardon my necro-posting. 

I'm just adding a comment to this closed issue because it's the first result on google when investigating the issue.
There are different ways to solve this problem but the most straight forward is:

	sudo -E <app>
	
See the [sway wiki](https://github.com/swaywm/sway/wiki#wayland-wont-let-me-run-apps-as-root) for more information
