### ISSUE TITLE
Click and drag to resize windows is borked

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/sway#186]
All of the windows involved disappaer.

**Comment by zetok** [comment]
Problem with windows disappearing is also reproducible by quickly changing size of window even with a keyboard (`$mod + r` + `$mod + j`).

When doing that on 73af58152b24e0cfe28f6c613e8e7523ffb515fc windows become "invisible" and "freeze" sway. By r-clicking in a terminal that became invisible I somehow managed to unfreeze sway, and from there I could close one of invisible terminals - the other one became visible.

With 73af58152b24e0cfe28f6c613e8e7523ffb515fc reverted resizing doesn't cause sway to "freeze" and it's a lot harder to make windows "invisible",

On a downside of revert, resizing is a lot slower, and there are more graphical glitches when resizing.

**Comment by Cloudef** [comment]
So far we know this happens with X windows and when multiple are resized at once(?). (May be wlc)

**Comment by somebears** [comment]
this might not be of importance as I cannot reproduce this, but in the case it can help resolving this:

I had opened two terminals, when resizing($mod + right mouse) only one of the windows disappeared (instead of the usual both) the second one seemed to be resized to a very small size(partially visible scrollbar). While I would have expected that it would reside on either side of the screen or in the centre, but it was roughly one third into the middle from the left side of the screen.

When attempting to resize it to the proper size, the window disappeared.

**Comment by SirCmpwn** [comment]
@Cloudef any luck in figuring this one out? I'm 99% sure it's not on the sway end.

**Comment by Cloudef** [comment]
No I haven't yet. I'll try to get on it today. Is it confirmed that this only happens with X windows however?

**Comment by SirCmpwn** [comment]
Yes, that seems to be the case.

**Comment by Cloudef** [comment]
Should be fixed now.

**Comment by SirCmpwn** [comment]
Yep! Thanks!
