### ISSUE TITLE
Small gaps showing. 

### ISSUE THREAD

**Issue by dayflip** [SirCmpwn/sway#392]
Having small gaps showing. Never have this happen when I had no bar. It only happens with swaybar. 
http://postimg.org/image/qq0dyyzp3/full/

**Comment by kon14** [comment]
This is related to what I've noticed in #303 (it's the same thing, only the issue is meant to cover another bug).
Reposting the important part for convenience:

Launching multiple windows horizontally (in the same workspace) creates a gap on the right end of the screen (gaps disabled), the width of which seems to increase the more windows you launch.

It's probably due to remaining pixels not being allocated to any of the windows (while dividing the screen's width / windows) but, since the gap is present on workspaces with even numbers of windows too (in that case horizontal pixels should divide perfectly), I'm kinda doubtful.

The above behaviour is reproduceable at any time on my 1366x768 display and might possibly affect vertical stacks too (it does affect them). The number of displayed windows required for the gap to show up might depend on the resolution.
