### ISSUE TITLE
Freeze when scrolling fast between workspaces

### ISSUE THREAD

**Issue by maximiliankaul** [SirCmpwn/sway#892]
Sway freezes when I open multiple workspaces and then use the mousewheel in the bar to switch between them very quickly.
Setting `wrap_scroll` does not make a difference.
I can not reproduce the issue when switching via bash like this (so I assume it's not the speed but something with the mousewheel):

```
for i in `seq 1 1000`; do
  swaymsg workspace prev_on_output
  swaymsg workspace next_on_output
done
```

The only options I have when the freeze happens is to hibernate the laptop using the power key (which does not help because it's still frozen when resuming) and to reboot.

Do you need additional information?

Versions (all Arch Linux packages):
sway version: 0.9-1:
wlc: 0.0.5-1
wayland: 1.11.0-1
[sway.log.txt](https://github.com/SirCmpwn/sway/files/465554/sway.log.txt)
Thanks for a awesome project :)

**Comment by Kamiyaa** [comment]
I seem to be having similar freezes. Though, mine are not from scrolling between workspaces, but just switching between them using mod+num rapidly.

**Comment by jarias** [comment]
Having the same issue here let me know what information I can provide to help fix this.

**Comment by SirCmpwn** [comment]
>Having the same issue here let me know what information I can provide to help fix this.

The output of `git diff` on a branch with the feature patched would be a great start

**Comment by Kamiyaa** [comment]
just wondering if it's possible to have the scrolling between work spaces feature something that can be toggled during compile time. :x

**Comment by ilyaluk** [comment]
I've debugged this issue. That's IPC problem. When user scrolls or clicks in swaybar, [ipc_send_workspace_command](https://github.com/SirCmpwn/sway/blob/master/swaybar/ipc.c#L11) is being called, which calls [ipc_single_command](https://github.com/SirCmpwn/sway/blob/master/common/ipc-client.c#L91), which waits for a reply and blocks swaybar thread until response from socket. But the response to this command not being sent by IPC server until all subscriptions processed. swaybar opens second socket for event processing and subscribes to workspace updates.

Looks like when user scrolling too fast, buffer of event socket fills, which causes deadlock (sway cannot write to event socket because buffer is full, therefore cannot send response, and swaybar infinitely waits for this response).

I'm not sure what is the best architectural solution.

**Comment by SirCmpwn** [comment]
Probably best to change swaybar to avoid submitting so many IPC requests in a row.

**Comment by SirCmpwn** [comment]
And update sway to avoid the deadlock
