### ISSUE TITLE
Setting wallpaper silently fails

### ISSUE THREAD

**Issue by qlyoung** [SirCmpwn/sway#895]
On a fresh Ubuntu 16.04.1 netinstall, after build + install + config of latest wlc and sway, the wallpaper remains unset and displays only a black screen. This occurs when using a single color wall as well.

Log: https://spit.mixtape.moe/view/27812180
Conf: https://spit.mixtape.moe/view/0066fe57

Relevant snippets:

```
09/11/16 20:47:35 - handling config command 'output LVDS-1 res 1366x768 pos 0,0 bg ~/pictures/wallpapers/eva-01.jpg fill'
09/11/16 20:47:35 - find_handler(output) 0
09/11/16 20:47:35 - Config stored for output LVDS-1 (enabled:-1) (1366 x 768 @ 0, 0 scale 1) (bg /home/hardware/pictures/wallpapers/eva-01.jpg fill)
09/11/16 20:47:35 - handling config command 'output HDMI-A-1 res 1920x1080 pos 1366,0 bg ~/pictures/wallpapers/eva-01.jpg fill'
09/11/16 20:47:35 - find_handler(output) 0
09/11/16 20:47:35 - Config stored for output HDMI-A-1 (enabled:-1) (1920 x 1080 @ 1366, 0 scale 1) (bg /home/hardware/pictures/wallpapers/eva-01.jpg fill)
```

later...

```
09/11/16 20:47:36 - Setting background for output 0 to /home/hardware/pictures/wallpapers/eva-01.jpg
09/11/16 20:47:36 - Setting background for output 1 to /home/hardware/pictures/wallpapers/eva-01.jpg
```

but background remains solid black.

**Comment by serussell** [comment]
Hi @qlyoung,

I'm finding it nigh-on impossible to install Sway on Ubuntu; I can't get WLC to install.  There are no packages for it, and the requirements information is skeletal at best.  I did my best dredging up the various dependencies, and am now stuck at a bunch of undefined references during linking libwlc, and Google fails to find any references to most of the missing symbols.

So: any pointers on how you got as far as getting Sway to actually install?  This is beyond bleeding edge, and I understand that. It's built on a foundation of bleeding edges, from Wayland on up.  Any pointers to how you got past the worst stumbling blocks you encountered would be a service.

P.S.  This question has nothing to do with this ticket, but since Github removed any ability to direct message a user, this is about the only way to get a message to somebody.  Sorry about that.

**Comment by 4e554c4c** [comment]
@serussel, The IRC channel for sway is probably the best place for questions like this. It is #sway on irc.freenode.net and you can join the webchat [here](http://webchat.freenode.net/?channels=sway&uio=d4). However, they would probably tell you to read the wiki, because there is already a page dedicated to [installing on Debian based systems](https://github.com/SirCmpwn/sway/wiki/Debian-installation-guide) which I think is what you want. Good luck!

**Comment by qlyoung** [comment]
@serussell I can confirm that following the wiki page for Debian based systems linked by @4e554c4c , starting from an Ubuntu Minimal install, is how I accomplished this.

**Comment by lheckemann** [comment]
@qlyoung try converting the image to png and using that — that fixed it for me. It should be documented that [png is assumed unless using gdk_pixbuf](https://github.com/SirCmpwn/sway/blob/master/swaybg/main.c#L95).

**Comment by qlyoung** [comment]
Just tried it on the same version of Sway that I opened this issue with and yep, png's work just fine. Thanks a bunch!

I'll close out this issue since you've got a PR open for it.
