### ISSUE TITLE
Gnome terminal exits normally when you try to use any of the drop-down menus

### ISSUE THREAD

**Issue by Laaas** [SirCmpwn/sway#978]
e.g. File, Edit, View.

**Comment by SirCmpwn** [comment]
Come on dude, you have got to start providing more detail in your bug reports.

**Comment by bananaoomarang** [comment]
Likely related: 

https://github.com/Cloudef/wlc/issues/210

**Comment by Drakulix** [comment]
I can confirm this issue, although I it very likely just https://github.com/Cloudef/wlc/issues/210 , as I have encountered this bug with nautilus as well.

Fedora 24, sway and wlc installed via testing repo (build date 2016-10-26). Since this version is quite outdated, I decided against reporting it.
